server:
  port: 80

build_name: @project.name@
build_version: @project.version@

spring:
  datasource:
    username: root
    password: Fiap1234
    url: jdbc:mysql://localhost:3306/abc_tech
  jpa:
    hibernate:            
      ddl-auto: none
    show-sql: true

